<?php
// $Id: xoops_version.php,v 1.16 2009/10/26 11:46:31 nobu Exp $
$modversion =
    array('name' => _MI_REFPAGE_NAME,
	  'version' => "1.92",
	  'description' => _MI_REFPAGE_DESC,
	  'author' => "Nobuhiro Yasutomi ( http://myht.org/ )",
	  'credits' => "Nobuhiro Yasutomi",
	  'help' => "help.html",
	  'license' => "GPL see LICENSE",
	  'official' => 0,
	  'image' => "refpage_slogo2.png",
	  'dirname' => basename(dirname(__FILE__)));

// Sql file (must contain sql generated by phpMyAdmin or phpPgAdmin)
// All tables should not have any prefix!
$modversion['sqlfile']['mysql'] = "sql/mysql.sql";
//$modversion['sqlfile']['postgresql'] = "sql/pgsql.sql";

// Tables created by sql file (without prefix!)
$modversion['tables'][] = "refpage";
$modversion['tables'][] = "refpage_ref";
$modversion['tables'][] = "refpage_log";

// Admin things
$modversion['hasAdmin'] = 1;
$modversion['adminindex'] = "admin/index.php";
$modversion['adminmenu'] = "admin/menu.php";

// Templates
$modversion['templates'][] =
    array('file' => 'refpage_index.html', 'description' => _MI_RP_INDEX_TPL);
$modversion['templates'][] =
    array('file' => 'refpage_referer.html', 'description' => _MI_RP_REFERER_TPL);

//Blocks
$modversion['blocks'][1] =
    array('file' => "refpage.php",
	  'name' => _MI_REFPAGE_BNAME,
	  'description' => "Logging refpage and show it",
	  'show_func' => "b_refpage_log_show",
	  'edit_func' => "b_refpage_log_edit",
	  'template' => "refpage_block_menu.html",
	  'can_clone' => true,
	  // Show Referer|Lists|Strict Check
	  'options' => "8|18");

// Menu
$modversion['hasMain'] = 1;
$modversion['sub'][] = array('name' => _MI_REFPAGE_SMENU1,
			     'url' => "index.php?id=all");

// Config
$modversion['hasconfig'] = 1;
$modversion['config'][]=array('name' => 'exclude',
			      'title' => '_MI_RPCF_EXCLUDE',
			      'description' => '_MI_RPCF_EXCLUDE_DESC',
			      'formtype' => 'textarea',
			      'valuetype' => 'string',
			      'default' => _MI_RPCF_EXCLUDE_DEF);
$modversion['config'][]=array('name' => 'include',
			      'title' => '_MI_RPCF_INCLUDE',
			      'description' => '_MI_RPCF_INCLUDE_DESC',
			      'formtype' => 'textarea',
			      'valuetype' => 'string',
			      'default' => _MI_RPCF_INCLUDE_DEF);
$modversion['config'][]=array('name' => 'auto_check',
			      'title' => '_MI_RPCF_AUTOCHECK',
			      'description' => '_MI_RPCF_AUTOCHECK_DESC',
			      'formtype' => 'yesno',
			      'valuetype' => 'int',
			      'default' => 1);
$modversion['config'][]=array('name' => 'block_show',
			      'title' => '_MI_RPCF_BLOCKSHOW',
			      'description' => '_MI_RPCF_BLOCKSHOW_DESC',
			      'formtype' => 'yesno',
			      'valuetype' => 'int',
			      'default' => 1);
$modversion['config'][]=array('name' => 'list_max',
			      'title' => '_MI_RPCF_LISTMAX',
			      'description' => '_MI_RPCF_LISTMAX_DESC',
			      'formtype' => 'text',
			      'valuetype' => 'int',
			      'default' => 25);
$modversion['config'][]=array('name' => 'title_len',
			      'title' => '_MI_RPCF_TITLELEN',
			      'description' => '_MI_RPCF_TITLELEN_DESC',
			      'formtype' => 'text',
			      'valuetype' => 'int',
			      'default' => 60);
$modversion['config'][]=array('name' => 'ctext_len',
			      'title' => '_MI_RPCF_CTEXTLEN',
			      'description' => '_MI_RPCF_CTEXTLEN_DESC',
			      'formtype' => 'text',
			      'valuetype' => 'int',
			      'default' => 200);
$modversion['config'][]=array('name' => 'ctext_len',
			      'title' => '_MI_RPCF_CTEXTLEN',
			      'description' => '_MI_RPCF_CTEXTLEN_DESC',
			      'formtype' => 'text',
			      'valuetype' => 'int',
			      'default' => 200);
$modversion['config'][]=array('name' => 'expire',
			      'title' => '_MI_RPCF_EXPIREDAY',
			      'description' => '_MI_RPCF_EXPIREDAY_DESC',
			      'formtype' => 'text',
			      'valuetype' => 'int',
			      'default' => 30);
$modversion['config'][]=array('name' => 'threshold',
			      'title' => '_MI_RPCF_THRESHOLD',
			      'description' => '_MI_RPCF_THRESHOLD_DESC',
			      'formtype' => 'text',
			      'valuetype' => 'int',
			      'default' => 2);
?>
